name: "Publish container"

on:
  workflow_call:
    inputs:
      artifacts_name:
        required: true
        type: string
      artifacts_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string
      project_file:
        required: true
        type: string

jobs:
  publish-container-image:
    name: Publish Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifacts_name }}
          path: ${{ inputs.artifacts_path }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ vars.CONTAINER_REGISTRY_NAME }}

      - name: Build and push container image
        run: dotnet publish ${{ inputs.project_file }} -t:PublishContainer -p ContainerRegistry=${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io -p ContainerImageTags='"${{ inputs.version }};latest"' -p ContainerRepository=${{ inputs.image_name }}